openapi: 3.0.3
info:
  title: My API
  version: 1.0.0
servers:
  - url: "${API_BASE_URL}"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: "${API_KEY_HEADER_NAME}"
security:
  - ApiKeyAuth: []
paths: {}
