openapi: 3.0.3
info: { title: Mini API, version: 1.0.0 }
paths:
  /ping:
    get:
      summary: Ping
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
