name: Build & Publish Swagger UI (multi-apis)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20           # no cache to avoid lockfile errors

      - name: Install deps
        run: npm install

      # Build API folders using your script (reads .env, .env.local, then process.env)
      - name: Build API folders
        env:
          # from repo secrets https://github.com/openTdataCH/test-api-explorer/settings/secrets/actions
          API_KEY_FORMATION_SERVICE: ${{ secrets.API_KEY_FORMATION_SERVICE }}
          API_KEY_OJP1: ${{ secrets.API_KEY_OJP1 }}
          API_KEY_OJP2: ${{ secrets.API_KEY_OJP2 }}
        run: |
          node scripts/render-openapi.mjs --api=formation
          node scripts/render-openapi.mjs --api=ojp1.0
          node scripts/render-openapi.mjs --api=ojp2.0

      # Build local swagger
      - name: Add Swagger UI assets
        run: |
          mkdir -p dist/assets
          cp node_modules/swagger-ui-dist/swagger-ui.css dist/assets/
          cp node_modules/swagger-ui-dist/swagger-ui-bundle.js dist/assets/
          cp node_modules/swagger-ui-dist/swagger-ui-standalone-preset.js dist/assets/
          cp node_modules/swagger-ui-dist/*bundle.js.map dist/assets/ || true

      # Root landing page to avoid 404 on /api-view/
      - name: Add landing page
        run: |
          cp site/index.html dist/index.html
          cp dist/index.html dist/404.html || true
          touch dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
