name: Build & Publish Swagger UI Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install tooling
        run: |
          npm i --no-save swagger-ui-dist
          sudo apt-get update
          sudo apt-get install -y gettext-base

      # Inject only the variables you expect (prevents messing up $ref)
      - name: Substitute env into OpenAPI
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          API_KEY_HEADER_NAME: ${{ secrets.API_KEY_HEADER_NAME }}
        run: |
          VARS='${API_BASE_URL} ${API_KEY_HEADER_NAME}'
          envsubst "$VARS" < openapi/openapi.template.yaml > openapi.yaml
          echo "::add-mask::${API_BASE_URL}"
          echo "::add-mask::${API_KEY_HEADER_NAME}"

      - name: Build static Swagger UI site
        run: |
          mkdir -p dist
          # Copy UI assets (including .map to avoid 404 in DevTools)
          cp node_modules/swagger-ui-dist/swagger-ui.css dist/
          cp node_modules/swagger-ui-dist/swagger-ui-bundle.js dist/
          cp node_modules/swagger-ui-dist/swagger-ui-standalone-preset.js dist/
          cp node_modules/swagger-ui-dist/*bundle.js.map dist/ || true
          # Your resolved spec
          cp openapi.yaml dist/

          # Minimal HTML (local assets, relative spec path works on GitHub Pages)
          cat > dist/index.html <<'HTML'
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>API Docs</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="./swagger-ui.css">
  <style>html,body,#swagger{height:100%;margin:0}</style>
</head>
<body>
  <div id="swagger"></div>
  <script src="./swagger-ui-bundle.js"></script>
  <script src="./swagger-ui-standalone-preset.js"></script>
  <script>
    window.ui = SwaggerUIBundle({
      url: './openapi.yaml',
      dom_id: '#swagger',
      deepLinking: true,
      presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
      layout: 'StandaloneLayout',
      persistAuthorization: false
    });
  </script>
</body>
</html>
HTML

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
